name: Deploy loopus with Docker

on:
  pull_request:
    types: [closed]
    branches:
      - release
      - develop

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Generate UUID as version tag
        id: uuid
        run: echo "TAG=ver-$(uuidgen)" >> $GITHUB_ENV

      - name: Build and push BE image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/loopus-be:${{ env.TAG }}"

      - name: Stop, Clean, Pull, and Run Backend Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "üõë Stopping old container"
            docker stop loopus-be || true
            docker rm loopus-be || true

            echo "üßπ Removing old backend images (excluding current)"
            docker images '${{ secrets.DOCKER_USERNAME }}/loopus-be' --format '{{.Repository}}:{{.Tag}}' | grep -v "${{ env.TAG }}" | xargs -r docker rmi || true

            echo "üì• Pulling new image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/loopus-be:${{ env.TAG }}

            echo "üåê Ensuring network exists"
            docker network create loopus-net || true

            echo "üöÄ Running container"
            docker run -d \
            --name loopus-be \
            --network loopus-net \
            -p 8080:8080 \
            -e CLIENT_KEY=${{ secrets.CLIENT_KEY }} \
            -e API_KEY=${{ secrets.API_KEY }} \
            -e CHECKSUM_KEY=${{ secrets.CHECKSUM_KEY }} \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            -v /var/www/uploads:/var/www/uploads \
            ${{ secrets.DOCKER_USERNAME }}/loopus-be:${{ env.TAG }}